# Generated by Django 4.2.2 on 2023-06-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('question', models.TextField()),
            ],
            options={
                'verbose_name': 'Завяка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
