# Generated by Django 4.2.2 on 2023-06-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='question',
            field=models.TextField(verbose_name='Запрос'),
        ),
    ]
